name: act
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      gcp-project:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo -e "I am working in [${{ inputs.environment }}]. \nMy gcp project is [${{ inputs.gcp-project }}]. \nMy service account key is [${{ secrets.SERVICE_ACCOUNT_KEY }}]."
