name: deploy-prod

on:
  push:
    branches:
      - master

jobs:  
  deploy:
    uses: ./.github/workflows/blank.yml
    with:
      environment: prod
      gcp-project: gcp-blah-blah-prod
      app-engine-url: 'https://google.com'
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
