name: deploy-dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:  
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      gcp-project: gcp-blah-blah-dev
