name: deploy-dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:  
  deploy:
    uses: ./.github/workflows/blank.yml
    with:
      environment: dev
      gcp-project: gcp-blah-blah-dev
      app-engine-url: 'https://google.com'
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
